# 这是一个名为'meshcnn'的环境配置文件
name: meshcnn
# 'channels'定义了包的来源
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6.8  # Python的版本
  - cython=0.27.3  # Cython的版本，一个Python的C语言扩展
  - pytorch=1.5.1  # PyTorch的版本，一个深度学习框架
  - numpy=1.15.0    # Numpy的版本，一个用于数值计算的库
  - matplotlib=3.0.3  # Matplotlib的版本，一个用于绘图的库
  - pip # Pip，Python的包管理器
   # 通过pip安装的额外依赖包
  - pip:
    - tensorboard  # TensorBoard，一个用于可视化神经网络训练结果的工具
    - tensorboardX # TensorBoardX，一个TensorBoard的扩展
    - pytest==5.1.1 # PyTest的版本，一个用于Python的测试框架
